export const LAB_TESTS = [
  "Haemoglobin", "Sugar", "Urea", "Creatine", "Uric acid", "Magnesium", "Ceruloplasmin", "Cupper", "Cholesterol",
  "Triglyceride", "HDL", "VLDL", "Calcium", "Phosphorus", "Albumin", "Total protein", "Micro albumin (Urine)",
  "T.S.B", "Direct bilirubin", "inDirect bilirubin", "GPT", "GOT", "Alkaline phosphatase", "Gamma GT (GGT)",
  "Na, K, CL", "Total iron", "TIBC", "Transferrin", "Lipase", "Amylase", "Zn", "LH", "FSH", "Prolactin",
  "Progesterone", "Testosterone", "Free Testosterone", "Estradiol", "AMH", "17_OH_Prog", "DHEA", "Cortisol",
  "ACTH", "PTH", "Growth H", "Aldosterone", "Renin", "Pro BNP (titer)", "Inhibin B", "25.OH-Vit D Total",
  "Calcitonin", "Vitamin B12", "Folic acid", "Ferritin", "T3", "T4", "TSH", "Free thyroxin index FTI",
  "T3 UP Take", "Thyroglobulin", "Free T3", "Free T4", "Anti_ ΤΡΟ", "Anti Thyroglobulin Ab",
  "Thyrotropin receptor Ab (TRAB)", "LDH titer", "Creatin phosphokinase-total (CPK)",
  "Creatin phosphokinase-MB (CK MB)", "D-Dimer", "Troponin", "Myoglobulin titer", "CRP titer",
  "CRP highly sensitive", "CA 19.9", "CA 15.3", "CA 125", "AFP", "PSA", "Free PSA", "CEA", "B-HCG",
  "CA 27.29", "PT + PTT", "Blood Film+ CBC", "Retic", "D. Dimer", "In Direct Coombs T. (Rh Antibody Titer)",
  "Direct Coombs T. (Hemolytic Anemia)", "protein C", "protein S", "CBC", "Fibrinogen", "Lupus anticoagulant",
  "G6PD titer for child & adult", "Hb. Electrophoresis", "JAK2 Mutation by PCR (EDTA 5ml)",
  "Anti-Smooth muscle", "Anti-Mitochondria Ab", "Anti Smith Ab", "Anti_SS A (RO)", "Anti_SS B (LA)",
  "Anti_LKM", "Anti-Nuclear Ab /SLE", "ANCA_P (PR3)", "ANCA_C (MPO)", "Anti-Chlamydia IgG",
  "Anti-Chamydia IgM", "Toxoplasma IgG titer", "Toxoplasma IgM titer", "CMV IgG titer", "CMV IgM titer",
  "Rubella IgG titer", "Rubella IgM titer", "HSV IgG (I&II) titer", "HSV IgM (I&II) titer",
  "Anti cardiolipin IgG (ACL)", "Anti cardiolipin IgM (ACL)", "Anti phospholipid IgG (APL)",
  "Anti phospholipid IgM (APL)", "B2_Glyco protein IgG + IgM", "Anti-H.pylori Ab", "H.pylori Ag",
  "IGRA", "Urea Breath Test", "VDRL", "ΤPHA", "ASOT", "RF", "CRP (titer)", "HBV profile (combo)",
  "HBs Ag titer", "HBs Ab titer", "HCV Ab titer", "Syphilis titer", "IgM", "IgA", "IgG", "IgE",
  "C3 complement", "C4 complement", "Anti DS-DNA", "Anti CCP Ab", "Brucella IgG", "Brucella IgM",
  "ACE insertion / deletion (I/D)", "Human Platelet Antigen 1 (HPA-1) mutation",
  "Factor II (prothrombin) mutation", "B-Fibrinogen", "MTHFR C677T mutation", "PAI-1 mutation",
  "Apolipoprotein E (Apo E)", "E2/E3/E4 polymorphism", "ENA panel", "Anti Ganglioside profile",
  "Liver profile panel", "Paraneoplastic Panel", "Carbamzepin (Tegretol)", "Valproic acid (Depaken)",
  "Acetylcholine receptor Ab (ACHRAB)", "Anti MuSK-Ab", "anti Titin Ab",
  "Anti Glutamic Acid Decarboxylase (GAD-65)", "Inflammatory Myopathies", "Autoimmune Encephalitis Profile",
  "penal Paraneoplastic Neurolgic Syndromes profile", "Cytogenetic panel", "CFTR gene for cystic fibrosis",
  "CAH gene", "SMV gene for muscular atrophy (SMA)", "DMD gene for Duchenne & Becker muscular Dystrophy",
  "Full Thrombophilia panel screen in recurrent miscarriage in the first trimester",
  "Y-chromosome microdeletion", "Metabolic screen (MS/MS)", "HB V Viral load Real Time PCR",
  "HCV Viral load Real Time PCR", "HCV Genotype Real Time PCR", "TB Real Time PCR By Gene xpert",
  "JAK2 V617F (JAK2 Mutaion)", "HCV PCR By Gene Xpert", "HBV PCR By Gene Xpert",
  "Rubella virus-TORCH Infection", "Parvovirus B19-TORCH Infection", "Toxoplasma gondii-TORCH Infection",
  "HPV Genotype (14 types High Risk Oncogenic) - (SWAB)", "EBV", "CMV", "HHV6", "HLA Type B5",
  "HLA Type B51", "HLA Type B27", "Blood Culture", "Ascitic Fluid Culture", "Pus Culture", "Urine Culture",
  "Semen Culture", "Stool Culture", "Sputum Culture", "Ear Swab", "Throat Swab", "Synovial Fluid Culture",
  "Conjunctival Swab", "High Vaginal Swab", "Gram stain", "Acid Fast bacillus", "Wet Examination",
  "Direct Examination", "Food panel (64 Types)", "Food panel (100 Types) Soon", "Food print (220 Test)",
  "Food print (118 Test)", "Inhalation panel (30 Types)", "C-peptide", "Anti-Insulin Ab", "HbA1c", "Insulin",
  "Anti-Tissu trans glut. IgG", "Anti-Tissu trans glut. IgA", "Anti-Gliadin IgG", "Anti-Gliadin IgA",
  "Anti-Endomysel IgG", "Anti-Endomysel IgA", "Acetyl Choline (Ach)", "Anti Tissue IgG By Chorus",
  "Aquaporing 4 Ab (NMO)", "Acid phosphate", "Activated Protein-C resistance", "Activated Protein-S resistance",
  "Adeno Virus Abs", "Anti TSH Receptor Ab", "Adenosin deaminase", "Adenosin diphosphate", "ADH", "AFB",
  "Anti-Smith (Anti-Sm)", "Albumin / Creatinine Retio (ACR)", "Aldosteron", "Alpha-1 Anti trypsin",
  "Alpha Fetoprotein", "AMA", "AMH By ELISA", "Amyloid A", "Amyloid B", "Amyotrophic lateral Sclerosis (ALS)",
  "Anti Glycoprotein 210", "ANA By ELISA", "ANA Panel", "ANCA-C By Fluorescent", "ANCA-P By Fluorescent",
  "ANCA-C (By chorus)", "ANCA-P (By chorus)", "Angiotensin Converting Enzyme (ACE)", "Anti-SP 200", "Anti CCP",
  "Anti Gaspi Ab", "Anti LGI 1", "Anti NMD Ab", "Anti-phospholipid (G,M) each one", "Anti-phospholipid Ab",
  "Anti-prothrombin Ab", "Anti-SLA (Soluble liver Antigen )", "Anti sp 100", "Anti-Thrombin III",
  "Anti VGKC Ab", "Anti. TG", "Antibiotics Allergy (123 items)", "Anti-cardio lipin (G.M) each one",
  "Anti-cardio lipin Ab", "Anti-Gab Ab", "Anti-Insulin Receptor", "Anti-Intrinsic (Ab)",
  "Allergic bronchopulmonary aspergillosis (ABPA)", "Anti LKM", "Anti Deamidated gliadin peptide",
  "Anti-Acetylcholinesterase", "Amyloidosis Genetic Panal", "Anti Ri", "Anti YO", "Anti Hu",
  "APC gene (Adenomatous polyposis coli)", "Adrenaline", "Anti-MOG", "Anti-Parietal Cell Antibody (APA)",
  "Anti-Smooth Ab By Fluorescent", "Anti-Sperm Ab", "Acetone Level", "Anti-Tissue Transglutaminase (IgG,IgA)",
  "Any CD Marker", "Anti-GAD", "Atopy allergy", "AMH Cobas", "ANA By Chorus",
  "Anti Cardiolipin ( IgG,IgM) Chorus Each one", "Anti Phospholipid ( IgG,IgM) Chorus Each one",
  "Anti Tissue ( IgA) Chorus", "Aldolase", "Androstenedione", "Anti-Saccharomyces cerevisiae ab (ASCA)",
  "Anti GBM", "Anti-DPPX Ab", "ADAM13", "ACE inhibitor (angiotensin – converting inhibitor",
  "Anti-glycine receptor ab", "B2- Microglobulin", "B2-Glycoprotein", "Brucella by (2me)", "Bicarbonate (co2)",
  "Bile Acids", "Benz jones protein (Titer)", "Beta Cell Test", "Blood Culture I.D (Bact Alert)",
  "BMCYT ASSAY", "Benze Jones Protein", "BRCA1 & BRCA2", "Brucella (G)", "Brucella (M)", "Brucella IFAT",
  "BUN (Blood Urea Nitrogin )", "B.Group", "C1-Esterase Inhibitor", "CA-125", "CA15.3", "CA.19.9", "C1.q",
  "Candida", "Cabamazepine (Tegretol)", "Cholinesterase", "C1", "Chromatography", "Chromatography in Urine",
  "CBC,Blood Film", "Calprotectin Level", "CH50", "Chlamydiam (M,G)", "Chromogranin A",
  "Chromosomal analysis ( Karyotype )", "C2 (Complement2)", "Chromosomal Breakage", "Chromosomal Fragility Test",
  "Chron’s Disease", "Ck-MB,Troponin,Myoglubulin", "CMV(G+M) each one", "Coenzyme Q10", "Cold agglutinins",
  "Complements (C3+C4) each one", "Congenital Thrombocytopenia", "Coombs (Direct & indirect) each one",
  "Copper", "CASR Gene", "CYP2C9 genotype Determination", "Cosmetics Allergy", "CPK", "C-Reactive Protein",
  "CK-MB", "Cystatin C", "Cushing syndrome", "Cornelia de Lange Syndrome (CDLS)", "Cystin in WBC",
  "Cryptococcal Ab", "Culture & Sensitivity", "Cyclosporine (Sand immune)", "Cystic Fibrosis", "Cryo globulins",
  "Cystine", "Digoxin (Lanoxin)", "Drug Allergy For Chronic Disease", "Dehydration Free Testo",
  "Depakine (Valproic Acid), Free and Total", "Detergents Allergy", "Dystrophy Muscular", "DHEAs",
  "DMD(Duchene Muscular Dystrophy)", "Dopamine", "Drug Allergy (26 items) Adult", "Drug Allergy (26 items) Child",
  "Dystonia and Ataxia Panel", "Ds DNA by Fluorescent", "Drug Allergy For Vitamins", "Ds DNA by ELISA",
  "DHT", "E3", "EBV(IgG)", "EGFR Gene Mutation", "Ehlers Danlos Syndrome", "EBV(IgM)",
  "Electrolytes (Na,K,Cl,Ph,Ca) each one", "ECM-1 Gene Study", "Epidermolysis Bullosa", "Electrolytes in urine",
  "Endomysial Ab (G+A)", "Erythropoietin (EPO)", "ESR", "F.T.I", "Factor V Leiden PCR",
  "Familial hyperglycemia Genetic Test", "Familial hyperlipidemia Genetic Test",
  "Familial hyperthyroidism Genetic Test", "FBS", "Fish Technique For Married(13,16,18,21,X or",
  "Fish Techniques", "Fungal Culture", "Genetic Study for Albinism", "Genetic Study Alport Syndrome",
  "Gene Xpert for HIV Type 1", "Genetic Study for hereditary Eye Disorders", "Gene Xpert for TB",
  "Glycogen Storage Disease (GSD)", "Gene Screening for CAH", "Genetic Study for Bacterial",
  "Gliadin (IgG) By CHORUS", "Gliadin Ab by ELISA", "GFR (Glomerular Filtration rate)", "Genetic Epilepsy Panal",
  "Globulin", "Genetic Study For Osteoporosis", "Genetic & Hereditary Eye Disorders", "Guillain Barre Syndrome",
  "Genetic for Psoriasis", "Gonadotropin Releasing Hormone (GnRH)", "GSE", "Galactose", "Galactosemia", "GUE",
  "H. Pylori Ab", "H. Pylori Ag", "HLA-DR", "HOCM (Hypertrophic cardiomyopathy)", "Herpes Zoster Ab",
  "Hydroxyl tryptophan", "Hepcidin Level", "HLA-D98", "Hemoglobin M (Methemoglobinemia)", "HLA-D92", "HAV IgM",
  "HB Electrophoresis", "Hbs Ag", "HBV Profile", "HCV", "Hemophilia", "HFE Gene (Hemochromatosis)", "HIV",
  "HLA (B5,B27,B51)", "HLA-B50", "HEMOSIDRIN", "HLA-B55", "Home Allergy", "Homocysteine", "HPV",
  "HSV (G+M) each one", "HTLV-I & 2 Screen", "I.M. (Infectious Mononucleosis)", "IGF1", "IgG Index Profile",
  "IGg4+IgG1+IgG2+IgG3 Each one", "IGRA TEST (QFT)", "Immune Electrophoresis", "Immune Fixation",
  "Immunoglobulins (A,G,M) each one", "Inhalation Allergy", "Inhibin A", "Insects Bite Allergy",
  "Insulin antibodies", "Insulin Resistance", "Interleukin (any Type )", "Interleukin 6", "Iron", "Islet Antibody",
  "Islet antigen 2 (IA-2)", "ichthyosis vulgaris", "Jon Cunningham Virus", "Jak 2 V617 Gen test",
  "Kalazar Test IFAT", "Kappa Lambda Ration", "Kennedy’s Disease Spinal &Bulbar Muscular Atrophy",
  "Lactose Allergy", "Limb-girdle Muscular Dystrophy", "Lipoprotein 6", "Lactose level", "Lamictal",
  "Leber hereditary optic neuropathy genetic test for 12 Mutations", "LG2", "Lipoprotein (a)", "LDH",
  "Leishmania Rapid", "Leptin", "LH By Cobas", "LH By TOSOH", "Lipid Profile", "Liver Enzyme (each one )",
  "Lupus Latex Ab (SLE)", "Lysosomal Storage Disease", "Lysosome Sarcoidosis", "Lysozyme enzyme", "Lactate",
  "Measles Ab", "Melatonin", "Metabolic Screen NGS ( 258 gene )", "Metal Allergy", "Mixing Study",
  "Multi Allergy Panel", "Metabolic Screen(MS-MS)(71 items)", "Mastuda index", "Myoglobin Titer", "Metanephrin",
  "Methyl Malonic Acid", "Micro deletion Chromosome Y", "Micro deletion Chromosome X", "Milk Allergy",
  "MLPA Assay", "MTHFR II", "MTHFR I", "MTX level(Methotrexate)", "Mycoplasma", "MucopolySacchardosis (MPS)",
  "Mental Retardation Panel", "Multiplex Lower Respiratory", "Mutation of Ever 1 & Ever 2 genes",
  "Nitro Blue Tera diazole", "Nephrotic Syndrome", "Noradrenaline", "NMO-Ab", "Noradrenalin in urine",
  "Neonatal Screening", "NMP-22 marker for bladder cancer)", "Non-steroidal Anti Inflammatories (NSAID)",
  "Norepinephrine", "Obesity Panal", "Osmatic Fragility", "Osteogenesis Imperfecta", "Osmolality",
  "Oligoclonnal band IgG Index", "PML/RARA (promyelocytic leukemia)", "Pernicious Anemia", "Oxalate", "PAI-1",
  "PLA2 group 2 (Phospholipase A2 )", "PCR For Floria", "PAPP(Pregnancy Associated Plasma Protein A )",
  "PCR for (CFTR) gene", "Phenylketonuria (urine)", "PCR For Pertussis", "PT,PTT each one", "Pyruvate",
  "Protein Electrophoresis (in Urine)", "Predict Huntington Disease", "Phenylalanine Level",
  "Porphobilinogen (PBG)", "PCR For HEV", "PCR For HAV", "PGX Thrombo-strip Assay",
  "Peroxisomal Disorder Panel (PDP)", "PCR for Mycoplasma Pranvera", "PCR for Mycoplasma Hominis",
  "Pancreatic Poly Peptide", "PCR for Herpes V ( 1&2)", "Para neoplastic screen", "Parkinson Panel",
  "PCR Echinomycin Israelis", "PCR for AVL", "PCR for BK", "PCR for Brucella", "PCR for CMV", "PCR for EBV",
  "PCR for Giardia", "PCR for HBV", "PCR for HCV", "PCR for HCV+Genotype For HCV", "PCR for Herpes screen",
  "PCR for HIV (V.1)", "PCR for HIV (V.2)", "PCR for HPV(16,18 — High Risk)", "PCR for HPV (16,52 — High Risk)",
  "PCR for HPV (31,33 — High Risk)", "PCR for HPV (6,11 — Low Risk)(genital warts)", "PCR for Hydatid cysts",
  "PCR for Leishmania", "Prolactine By Cobas", "PCR FOR LN", "PCR for Mumps", "PCR for NMDA", "PCR for Parvovirus",
  "PCR for Rota Virus", "PCR for Rubella", "PCR for Salmonella", "PCR for Syphilis",
  "PCR for TB – Mycobacterium Tuberculosis", "PCR for Toxoplasma", "PCR for Zoster Virus", "PCR For filarial",
  "Pepsin", "Protein-electrophoresis for M-Band", "Porphyrin", "Primary Catecholamine’s", "PRL",
  "Pro Calcitonin", "Pro Insulin", "Pro-BNP", "PROG", "Protein", "Protein C Functional Activity",
  "Protein Electrophoresis", "Protein S Functional Activity", "Prothrombin Gene Mutation (G20210A Mutation R-T (PCR)",
  "Prothrombin Gene Mutation (G20238A)", "Proto Porphyries", "Protein/ Crea ratio", "PKhd1 Gene", "Quicki index",
  "QD2,QD8 (Genetic Test)", "Rb 1 Single Gene", "Renal Function (each one)", "Renin activity",
  "Renine Aldosterone", "Retinoschisis Juvenile X-linked", "Rett Syndrome,MECP2 Gene Full Gene Analysis",
  "RH Ab. Titer", "Rheumatoid factor", "Ricof Test", "Rose Bengal", "RUB (G+M)each one", "Rota Virus", "SDDA",
  "Sliver-Russel Syndrome", "Secretin", "SAT gene", "SMA(Spinal Muscular Atrophy)", "Spinocerebellar Ataxia (SCA)",
  "Schistosomiasis IFAT", "SSDA", "S.Estriol", "SCL-70", "Seminal Fluid Analysis", "Serotonin",
  "Sex Hormone Binding Globulin(SHBG)", "Sickling Test", "Smith (Sm)", "SS.A(RO)", "SS.B(LA)", "Stone Analysis",
  "Stool For Calprotectin Titer", "Stool for Occult Blood", "Succinyl acetone Test", "Sulfa Test Allergy",
  "Syphilis Titer (TPHA)", "Tumor Necrosis Factor (TNF)", "Tyrosine Kinase Level", "Tyrosine Kinase Genotype",
  "Thyroglobulin Binding Protein", "Tunnel Test For the Sperm", "T-Uptake", "Thyrotropin Releasing Hormone (TRH)",
  "Thrombosis factors(Each one)", "TPO By Cobas", "T.B (Rapid T.B Test )", "T.I.B.C",
  "T3,T4,TSH By TOSOH each one", "TESTO By TOSOH", "Testosterone By Cobas", "Thalassemia 5 Mutations",
  "Thyroglobulin Ab", "Thyroglobulin Ag", "Thyrotropin Receptor Blocking (TRB)", "T3,T4,TSH By Cobas each one",
  "Tissue (IgA) By Chorus", "Tissue (IgG) By Chorus", "Toxo (G+M) each one", "TPHA (Syphilis)",
  "TPMT (Thiopurine Methyltransferase)", "Triple Test ( β,A,and S.estriol)", "Troponin Titer", "Tryptase",
  "TSH Receptor Ab", "Urine For Dysmorphic and Isomorphic", "Urea Breath Test (C13)", "Urethral Discharge for GC",
  "Vasoactive Intestinal Peptide (Vip)", "Varicella Zoster Ab", "Vitamin A", "Vitamin B1", "Vitamin B2",
  "Vitamin B5", "Vitamin B6 (pyridoxal 5-phosphate (PLP), Pyridoxic Acid (PA)", "Vitamin B7", "Vitamin C",
  "Vitamin D3", "Vitamin E", "Vitamin (K1,K2,K3) each one", "Von Willebran factor",
  "Wilson’s Disease (ATP7B Gene)", "Widal Test (G,M)", "Werding Hoffman Disease", "Whole Exome Sequencing (WES)",
  "Zinc", "17-Hydroxy Progesterone", "1P/19q deletion", "21 hydroxylase Antibodies", "21-hydroxylase genes",
  "17.Keto.Steroids", "24 Houre collection For Electrolytes", "24 Hour Collection for Homo Vanillic acid",
  "24 Houre Urin Collection For Creatinine Clearance", "24 Hour Urin collection for Protein",
  "24 Hour Urin collection for VMA", "24 Hour Urin Collection for Copper", "24 Hour Urine for Creatinine",
  "24 Hour Urine for Albumin", "24 Hour Urine for Ca", "24 Hour Urine For Cortisol", "24 Hour Urine for Mg",
  "24 Hours Urine Collection for Urea", "5-HIAA (5 hydroxy Amino Acitic Acid)", "24 Urine for Urin Acid",
  "24 Hour Urine for Oxalate", "24 Hour Urine Micro Albumin", "24 Hour Urine Suger", "24 Hour Urine for Phosphorus"
];
