import { LabTestMetadata } from '../types';

export const LAB_TESTS_METADATA: LabTestMetadata[] = [
  { name: "Haemoglobin", section: "Hematology", parameter: "Haemoglobin", range: "13.0-17.0", unit: "g/dl", specimen: "Whole Blood" },
  { name: "Sugar", section: "Biochemistry", parameter: "Blood Glucose", range: "70-100 (Fasting)", unit: "mg/dL", specimen: "Serum" },
  { name: "Urea", section: "Biochemistry", parameter: "Blood Urea Nitrogen", range: "7-20", unit: "mg/dL", specimen: "Serum" },
  { name: "Creatine", section: "Biochemistry", parameter: "Creatinine", range: "0.7-1.3 (M), 0.6-1.1 (F)", unit: "mg/dL", specimen: "Serum" },
  { name: "Uric acid", section: "Biochemistry", parameter: "Uric Acid", range: "3.5-7.2 (M), 2.6-6.0 (F)", unit: "mg/dL", specimen: "Serum" },
  { name: "Magnesium", section: "Biochemistry", parameter: "Magnesium", range: "1.7-2.2", unit: "mg/dL", specimen: "Serum" },
  { name: "Ceruloplasmin", section: "Biochemistry", parameter: "Ceruloplasmin", range: "20-60", unit: "mg/dL", specimen: "Serum" },
  { name: "Cupper", section: "Biochemistry", parameter: "Copper", range: "70-140", unit: "µg/dL", specimen: "Serum" },
  { name: "Cholesterol", section: "Lipid Profile", parameter: "Total Cholesterol", range: "<200 Desirable", unit: "mg/dL", specimen: "Serum" },
  { name: "Triglyceride", section: "Lipid Profile", parameter: "Triglycerides", range: "<150 Desirable", unit: "mg/dL", specimen: "Serum" },
  { name: "HDL", section: "Lipid Profile", parameter: "HDL Cholesterol", range: ">40 (M), >50 (F)", unit: "mg/dL", specimen: "Serum" },
  { name: "LDL Cholesterol", section: "Lipid Profile", parameter: "LDL Cholesterol", range: "<100 Optimal", unit: "mg/dL", specimen: "Serum" },
  { name: "VLDL", section: "Lipid Profile", parameter: "VLDL Cholesterol", range: "2-30", unit: "mg/dL", specimen: "Serum" },
  { name: "Calcium", section: "Biochemistry", parameter: "Calcium", range: "8.6-10.2", unit: "mg/dL", specimen: "Serum" },
  { name: "Phosphorus", section: "Biochemistry", parameter: "Phosphorus", range: "2.5-4.5", unit: "mg/dL", specimen: "Serum" },
  { name: "Albumin", section: "Biochemistry", parameter: "Albumin", range: "3.5-5.0", unit: "g/dL", specimen: "Serum" },
  { name: "Total protein", section: "Biochemistry", parameter: "Total Protein", range: "6.0-8.3", unit: "g/dL", specimen: "Serum" },
  { name: "Micro albumin (Urine)", section: "Biochemistry", parameter: "Microalbumin", range: "<30", unit: "mg/L", specimen: "Urine" },
  { name: "T.S.B", section: "Liver Function", parameter: "Total Bilirubin", range: "0.1-1.2", unit: "mg/dL", specimen: "Serum" },
  { name: "Direct bilirubin", section: "Liver Function", parameter: "Direct Bilirubin", range: "0.0-0.3", unit: "mg/dL", specimen: "Serum" },
  { name: "inDirect bilirubin", section: "Liver Function", parameter: "Indirect Bilirubin", range: "0.1-0.9", unit: "mg/dL", specimen: "Serum" },
  { name: "GPT", section: "Liver Function", parameter: "ALT/SGPT", range: "0-41", unit: "U/L", specimen: "Serum" },
  { name: "GOT", section: "Liver Function", parameter: "AST/SGOT", range: "0-40", unit: "U/L", specimen: "Serum" },
  { name: "Alkaline phosphatase", section: "Liver Function", parameter: "Alkaline Phosphatase", range: "44-147", unit: "U/L", specimen: "Serum" },
  { name: "Gamma GT (GGT)", section: "Liver Function", parameter: "GGT", range: "0-60", unit: "U/L", specimen: "Serum" },
  { name: "Na, K, CL", section: "Electrolytes", parameter: "Sodium/Potassium/Chloride", range: "Na:136-145, K:3.5-5.0, Cl:98-106", unit: "mEq/L", specimen: "Serum" },
  { name: "Total iron", section: "Biochemistry", parameter: "Serum Iron", range: "60-170", unit: "µg/dL", specimen: "Serum" },
  { name: "TIBC", section: "Biochemistry", parameter: "TIBC", range: "250-370", unit: "µg/dL", specimen: "Serum" },
  { name: "Transferrin", section: "Biochemistry", parameter: "Transferrin", range: "200-360", unit: "mg/dL", specimen: "Serum" },
  { name: "Lipase", section: "Biochemistry", parameter: "Lipase", range: "0-160", unit: "U/L", specimen: "Serum" },
  { name: "Amylase", section: "Biochemistry", parameter: "Amylase", range: "28-100", unit: "U/L", specimen: "Serum" },
  { name: "Zn", section: "Biochemistry", parameter: "Zinc", range: "60-120", unit: "µg/dL", specimen: "Serum" },
  { name: "Prolactin", section: "Hormones", parameter: "Prolactin", range: "2-29 (F), 2-18 (M)", unit: "ng/mL", specimen: "Serum" },
  { name: "Testosterone", section: "Hormones", parameter: "Total Testosterone", range: "270-1070 (M)", unit: "ng/dL", specimen: "Serum" },
  { name: "Free Testosterone", section: "Hormones", parameter: "Free Testosterone", range: "9-30 (M)", unit: "pg/mL", specimen: "Serum" },
  { name: "AMH", section: "Hormones", parameter: "Anti-Mullerian Hormone", range: "1.0-3.5 (F reproductive)", unit: "ng/mL", specimen: "Serum" },
  { name: "Cortisol", section: "Hormones", parameter: "Cortisol", range: "6-23 (AM)", unit: "µg/dL", specimen: "Serum" },
  { name: "ACTH", section: "Hormones", parameter: "ACTH", range: "10-60 (AM)", unit: "pg/mL", specimen: "Plasma (EDTA)" },
  { name: "PTH", section: "Hormones", parameter: "Parathyroid Hormone", range: "15-65", unit: "pg/mL", specimen: "Serum" },
  { name: "Vitamin D (25-OH)", section: "Biochemistry", parameter: "Vitamin D (25-OH)", range: "30-100", unit: "ng/mL", specimen: "Serum" },
  { name: "Vitamin B12", section: "Biochemistry", parameter: "Vitamin B12", range: "200-900", unit: "pg/mL", specimen: "Serum" },
  { name: "Folic acid", section: "Biochemistry", parameter: "Folic Acid", range: "2.7-17.0", unit: "ng/mL", specimen: "Serum" },
  { name: "Ferritin", section: "Biochemistry", parameter: "Ferritin", range: "12-150 (F), 12-300 (M)", unit: "ng/mL", specimen: "Serum" },
  { name: "TSH", section: "Thyroid", parameter: "TSH", range: "0.45-4.50", unit: "µIU/mL", specimen: "Serum" },
  { name: "Free T3", section: "Thyroid", parameter: "Free T3", range: "2.0-4.4", unit: "pg/mL", specimen: "Serum" },
  { name: "Free T4", section: "Thyroid", parameter: "Free T4", range: "0.82-1.77", unit: "ng/dL", specimen: "Serum" },
  { name: "CRP titer", section: "Immunology", parameter: "C-Reactive Protein", range: "<10", unit: "mg/L", specimen: "Serum" },
  { name: "PSA", section: "Tumor Markers", parameter: "PSA (Total)", range: "<4.0", unit: "ng/mL", specimen: "Serum" },
  { name: "HbA1c", section: "Biochemistry", parameter: "Hemoglobin A1c", range: "<5.7% (normal)", unit: "%", specimen: "Whole Blood (EDTA)" }
];

export const LAB_TESTS = LAB_TESTS_METADATA.map(t => t.name);
