import { Medication } from '../types';

export const MEDICATIONS: Medication[] = [
  {
    id: "M001",
    itemName: "hydrogen peroxide 300 MG/ML Topical Solution",
    itemType: "Topical Solution",
    itemCategory: "Topicals",
    drugFormName: "TOPICAL SOLUTION",
    drugMeasurement: "ML",
    genericName: "hydrogen peroxide",
    strength: "300",
    usage: "TOPICAL",
    stock: 150
  },
  {
    id: "M002",
    itemName: "hydrogen peroxide 30 MG/ML Topical Solution",
    itemType: "Topical Solution",
    itemCategory: "Topicals",
    drugFormName: "TOPICAL SOLUTION",
    drugMeasurement: "ML",
    genericName: "hydrogen peroxide",
    strength: "30",
    usage: "TOPICAL",
    stock: 120
  },
  {
    id: "M003",
    itemName: "fluorouracil 10 MG/ML Topical Cream [Fluoroplex]",
    itemType: "Topical Cream",
    itemCategory: "Topicals",
    drugFormName: "CREAM",
    drugMeasurement: "Gram",
    genericName: "fluorouracil",
    strength: "10",
    usage: "TOPICAL",
    stock: 45
  },
  {
    id: "M004",
    itemName: "griseofulvin 165 MG Oral Tablet [Fulvicin P/G]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "griseofulvin",
    strength: "165",
    usage: "ORAL",
    stock: 80
  },
  {
    id: "M005",
    itemName: "hydrochlorothiazide 50 MG / triamterene 75 MG Oral Tablet [Maxzide]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "hydrochlorothiazide",
    strength: "50",
    usage: "ORAL",
    stock: 200
  },
  {
    id: "M006",
    itemName: "hydrochlorothiazide 25 MG / triamterene 37.5 MG Oral Tablet [Maxzide]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "hydrochlorothiazide",
    strength: "25",
    usage: "ORAL",
    stock: 180
  },
  {
    id: "M007",
    itemName: "desoximetasone 2.5 MG/ML Topical Cream [Topicort]",
    itemType: "Topical Cream",
    itemCategory: "Topicals",
    drugFormName: "CREAM",
    drugMeasurement: "Gram",
    genericName: "desoximetasone",
    strength: "2.5",
    usage: "TOPICAL",
    stock: 60
  },
  {
    id: "M008",
    itemName: "desoximetasone 0.0005 MG/MG Topical Gel [Topicort]",
    itemType: "Topical Gel",
    itemCategory: "Topicals",
    drugFormName: "GEL",
    drugMeasurement: "Gram",
    genericName: "desoximetasone",
    strength: "0.0005",
    usage: "TOPICAL",
    stock: 35
  },
  {
    id: "M009",
    itemName: "desoximetasone 0.0025 MG/MG Topical Ointment [Topicort]",
    itemType: "Topical Ointment",
    itemCategory: "Topicals",
    drugFormName: "OINTMENT",
    drugMeasurement: "Gram",
    genericName: "desoximetasone",
    strength: "0.0025",
    usage: "TOPICAL",
    stock: 40
  },
  {
    id: "M010",
    itemName: "ichthammol 0.2 MG/MG Topical Ointment",
    itemType: "Topical Ointment",
    itemCategory: "Topicals",
    drugFormName: "OINTMENT",
    drugMeasurement: "Gram",
    genericName: "ichthammol",
    strength: "0.2",
    usage: "TOPICAL",
    stock: 110
  },
  {
    id: "M011",
    itemName: "primidone 250 MG Oral Tablet",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "primidone",
    strength: "250",
    usage: "ORAL",
    stock: 90
  },
  {
    id: "M012",
    itemName: "glycopyrrolate 2 MG Oral Tablet [Robinul]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "glycopyrrolate",
    strength: "2",
    usage: "ORAL",
    stock: 130
  },
  {
    id: "M013",
    itemName: "hydrocortisone 1.67 MG/ML Enema [Cortenema]",
    itemType: "Enema",
    itemCategory: "Enemas",
    drugFormName: "ENEMA",
    drugMeasurement: "Each",
    genericName: "hydrocortisone",
    strength: "1.67",
    usage: "RECTAL",
    stock: 25
  },
  {
    id: "M014",
    itemName: "lincomycin 300 MG/ML Injectable Solution [Lincocin]",
    itemType: "Injectable Solution",
    itemCategory: "Injectables",
    drugFormName: "INJECTABLE SOLUTION",
    drugMeasurement: "ML",
    genericName: "lincomycin",
    strength: "300",
    usage: "PARENTERAL",
    stock: 50
  },
  {
    id: "M015",
    itemName: "hydrocortisone 0.025 MG/MG Topical Ointment",
    itemType: "Topical Ointment",
    itemCategory: "Topicals",
    drugFormName: "OINTMENT",
    drugMeasurement: "Gram",
    genericName: "hydrocortisone",
    strength: "0.025",
    usage: "TOPICAL",
    stock: 200
  },
  {
    id: "M016",
    itemName: "hydrocortisone 10 MG/ML Topical Lotion",
    itemType: "Topical Lotion",
    itemCategory: "Topicals",
    drugFormName: "LOTION",
    drugMeasurement: "ML",
    genericName: "hydrocortisone",
    strength: "10",
    usage: "TOPICAL",
    stock: 140
  },
  {
    id: "M017",
    itemName: "desonide 0.5 MG/ML Topical Cream [Tridesilon]",
    itemType: "Topical Cream",
    itemCategory: "Topicals",
    drugFormName: "CREAM",
    drugMeasurement: "Gram",
    genericName: "desonide",
    strength: "0.5",
    usage: "TOPICAL",
    stock: 85
  },
  {
    id: "M018",
    itemName: "fluocinonide 0.5 MG/ML Topical Cream",
    itemType: "Topical Cream",
    itemCategory: "Topicals",
    drugFormName: "CREAM",
    drugMeasurement: "Gram",
    genericName: "fluocinonide",
    strength: "0.5",
    usage: "TOPICAL",
    stock: 70
  },
  {
    id: "M019",
    itemName: "fluocinonide 0.0005 MG/MG Topical Ointment",
    itemType: "Topical Ointment",
    itemCategory: "Topicals",
    drugFormName: "OINTMENT",
    drugMeasurement: "Gram",
    genericName: "fluocinonide",
    strength: "0.0005",
    usage: "TOPICAL",
    stock: 55
  },
  {
    id: "M020",
    itemName: "halcinonide 1 MG/ML Topical Cream",
    itemType: "Topical Cream",
    itemCategory: "Topicals",
    drugFormName: "CREAM",
    drugMeasurement: "Gram",
    genericName: "halcinonide",
    strength: "1",
    usage: "TOPICAL",
    stock: 30
  },
  {
    id: "M021",
    itemName: "salicylic acid 20 MG/ML Topical Lotion",
    itemType: "Topical Lotion",
    itemCategory: "Topicals",
    drugFormName: "LOTION",
    drugMeasurement: "ML",
    genericName: "salicylic acid",
    strength: "20",
    usage: "TOPICAL",
    stock: 120
  },
  {
    id: "M022",
    itemName: "mupirocin 0.02 MG/MG Topical Ointment [Bactroban]",
    itemType: "Topical Ointment",
    itemCategory: "Topicals",
    drugFormName: "OINTMENT",
    drugMeasurement: "Gram",
    genericName: "mupirocin",
    strength: "0.02",
    usage: "TOPICAL",
    stock: 160
  },
  {
    id: "M023",
    itemName: "rifabutin 150 MG Oral Capsule [Mycobutin]",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "rifabutin",
    strength: "150",
    usage: "ORAL",
    stock: 45
  },
  {
    id: "M024",
    itemName: "fluvastatin 40 MG Oral Capsule [Lescol]",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "fluvastatin",
    strength: "40",
    usage: "ORAL",
    stock: 90
  },
  {
    id: "M025",
    itemName: "ciprofloxacin 3 MG/ML Ophthalmic Solution [Ciloxan]",
    itemType: "Ophthalmic Solution",
    itemCategory: "Ophthalmics",
    drugFormName: "OPHTHALMIC SOLUTION",
    drugMeasurement: "ML",
    genericName: "ciprofloxacin",
    strength: "3",
    usage: "OPHTHALMIC",
    stock: 65
  },
  {
    id: "M026",
    itemName: "tolnaftate 10 MG/ML Topical Cream",
    itemType: "Topical Cream",
    itemCategory: "Topicals",
    drugFormName: "CREAM",
    drugMeasurement: "Gram",
    genericName: "tolnaftate",
    strength: "10",
    usage: "TOPICAL",
    stock: 140
  },
  {
    id: "M027",
    itemName: "alprostadil 0.02 MG Injection [Caverject]",
    itemType: "Injection",
    itemCategory: "Injectables",
    drugFormName: "INJECTION",
    drugMeasurement: "ML",
    genericName: "alprostadil",
    strength: "0.02",
    usage: "PARENTERAL",
    stock: 20
  },
  {
    id: "M028",
    itemName: "lamotrigine 100 MG Disintegrating Oral Tablet",
    itemType: "Disintegrating Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "DISINTEGRATING TABLET",
    drugMeasurement: "Each",
    genericName: "lamotrigine",
    strength: "100",
    usage: "ORAL",
    stock: 110
  },
  {
    id: "M029",
    itemName: "propantheline 15 MG Oral Tablet [Probanthine]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "propantheline",
    strength: "15",
    usage: "ORAL",
    stock: 75
  },
  {
    id: "M030",
    itemName: "cimetidine 200 MG Oral Tablet [Tagamet]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "cimetidine",
    strength: "200",
    usage: "ORAL",
    stock: 150
  },
  {
    id: "M031",
    itemName: "famotidine 20 MG Oral Tablet [Pepcid]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "famotidine",
    strength: "20",
    usage: "ORAL",
    stock: 220
  },
  {
    id: "M032",
    itemName: "famotidine 40 MG Oral Tablet [Pepcid]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "famotidine",
    strength: "40",
    usage: "ORAL",
    stock: 190
  },
  {
    id: "M033",
    itemName: "misoprostol 0.2 MG Oral Tablet [Cytotec]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "misoprostol",
    strength: "0.2",
    usage: "ORAL",
    stock: 60
  },
  {
    id: "M034",
    itemName: "mesalamine 400 MG Delayed Release Oral Tablet [Asacol]",
    itemType: "Delayed Release Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "DELAYED RELEASE TABLET",
    drugMeasurement: "Each",
    genericName: "mesalamine",
    strength: "400",
    usage: "ORAL",
    stock: 100
  },
  {
    id: "M035",
    itemName: "glycerin 2000 MG Rectal Suppository",
    itemType: "Rectal Suppository",
    itemCategory: "Suppositories",
    drugFormName: "SUPPOSITORY",
    drugMeasurement: "Each",
    genericName: "glycerin",
    strength: "2000",
    usage: "RECTAL",
    stock: 250
  },
  {
    id: "M036",
    itemName: "digoxin 0.0625 MG Oral Tablet [Lanoxin]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "digoxin",
    strength: "0.0625",
    usage: "ORAL",
    stock: 130
  },
  {
    id: "M037",
    itemName: "2 ML digoxin 0.25 MG/ML Injection",
    itemType: "Injection",
    itemCategory: "Injectables",
    drugFormName: "INJECTION",
    drugMeasurement: "ML",
    genericName: "digoxin",
    strength: "2",
    usage: "PARENTERAL",
    stock: 45
  },
  {
    id: "M038",
    itemName: "spironolactone 5 MG/ML Oral Suspension",
    itemType: "Oral Suspension",
    itemCategory: "Liquids",
    drugFormName: "SUSPENSION",
    drugMeasurement: "ML",
    genericName: "spironolactone",
    strength: "5",
    usage: "ORAL",
    stock: 90
  },
  {
    id: "M039",
    itemName: "doxazosin 1 MG Oral Tablet [Cardura]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "doxazosin",
    strength: "1",
    usage: "ORAL",
    stock: 110
  },
  {
    id: "M040",
    itemName: "doxazosin 2 MG Oral Tablet [Cardura]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "doxazosin",
    strength: "2",
    usage: "ORAL",
    stock: 120
  },
  {
    id: "M041",
    itemName: "doxazosin 4 MG Oral Tablet [Cardura]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "doxazosin",
    strength: "4",
    usage: "ORAL",
    stock: 105
  },
  {
    id: "M042",
    itemName: "lisinopril 2.5 MG Oral Tablet [Zestril]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "lisinopril",
    strength: "2.5",
    usage: "ORAL",
    stock: 300
  },
  {
    id: "M043",
    itemName: "lisinopril 5 MG Oral Tablet [Zestril]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "lisinopril",
    strength: "5",
    usage: "ORAL",
    stock: 280
  },
  {
    id: "M044",
    itemName: "lisinopril 10 MG Oral Tablet [Zestril]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "lisinopril",
    strength: "10",
    usage: "ORAL",
    stock: 260
  },
  {
    id: "M045",
    itemName: "lisinopril 20 MG Oral Tablet [Zestril]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "lisinopril",
    strength: "20",
    usage: "ORAL",
    stock: 240
  },
  {
    id: "M046",
    itemName: "ramipril 2.5 MG Oral Capsule [Altace]",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "ramipril",
    strength: "2.5",
    usage: "ORAL",
    stock: 150
  },
  {
    id: "M047",
    itemName: "ramipril 5 MG Oral Capsule [Altace]",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "ramipril",
    strength: "5",
    usage: "ORAL",
    stock: 140
  },
  {
    id: "M048",
    itemName: "inositol 500 MG Oral Capsule",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "inositol",
    strength: "500",
    usage: "ORAL",
    stock: 200
  },
  {
    id: "M049",
    itemName: "simvastatin 10 MG Oral Tablet [Zocor]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "simvastatin",
    strength: "10",
    usage: "ORAL",
    stock: 350
  },
  {
    id: "M050",
    itemName: "simvastatin 20 MG Oral Tablet [Zocor]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "simvastatin",
    strength: "20",
    usage: "ORAL",
    stock: 320
  },
  {
    id: "M051",
    itemName: "diazepam 2 MG Oral Tablet [Valium]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "diazepam",
    strength: "2",
    usage: "ORAL",
    stock: 180
  },
  {
    id: "M052",
    itemName: "diazepam 5 MG Oral Tablet [Valium]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "diazepam",
    strength: "5",
    usage: "ORAL",
    stock: 160
  },
  {
    id: "M053",
    itemName: "diazepam 10 MG Oral Tablet [Valium]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "diazepam",
    strength: "10",
    usage: "ORAL",
    stock: 140
  },
  {
    id: "M054",
    itemName: "lorazepam 1 MG Oral Tablet [Ativan]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "lorazepam",
    strength: "1",
    usage: "ORAL",
    stock: 200
  },
  {
    id: "M055",
    itemName: "clozapine 25 MG Oral Tablet [Clozaril]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "clozapine",
    strength: "25",
    usage: "ORAL",
    stock: 110
  },
  {
    id: "M056",
    itemName: "clozapine 100 MG Oral Tablet [Clozaril]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "clozapine",
    strength: "100",
    usage: "ORAL",
    stock: 95
  },
  {
    id: "M057",
    itemName: "risperidone 1 MG Oral Tablet [Risperdal]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "risperidone",
    strength: "1",
    usage: "ORAL",
    stock: 140
  },
  {
    id: "M058",
    itemName: "risperidone 2 MG Oral Tablet [Risperdal]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "risperidone",
    strength: "2",
    usage: "ORAL",
    stock: 130
  },
  {
    id: "M059",
    itemName: "risperidone 3 MG Oral Tablet [Risperdal]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "risperidone",
    strength: "3",
    usage: "ORAL",
    stock: 120
  },
  {
    id: "M060",
    itemName: "risperidone 4 MG Oral Tablet [Risperdal]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "risperidone",
    strength: "4",
    usage: "ORAL",
    stock: 110
  },
  {
    id: "M061",
    itemName: "phenelzine 15 MG Oral Tablet [Nardil]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "phenelzine",
    strength: "15",
    usage: "ORAL",
    stock: 50
  },
  {
    id: "M062",
    itemName: "isocarboxazid 10 MG Oral Tablet",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "isocarboxazid",
    strength: "10",
    usage: "ORAL",
    stock: 40
  },
  {
    id: "M063",
    itemName: "tranylcypromine 10 MG Oral Tablet [Parnate]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "tranylcypromine",
    strength: "10",
    usage: "ORAL",
    stock: 60
  },
  {
    id: "M064",
    itemName: "fluoxetine 20 MG Oral Capsule [Prozac]",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "fluoxetine",
    strength: "20",
    usage: "ORAL",
    stock: 280
  },
  {
    id: "M065",
    itemName: "metoclopramide 1 MG/ML Oral Solution",
    itemType: "Oral Solution",
    itemCategory: "Liquids",
    drugFormName: "ORAL SOLUTION",
    drugMeasurement: "ML",
    genericName: "metoclopramide",
    strength: "1",
    usage: "ORAL",
    stock: 150
  },
  {
    id: "M066",
    itemName: "nabilone 1 MG Oral Capsule [Cesamet]",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "nabilone",
    strength: "1",
    usage: "ORAL",
    stock: 25
  },
  {
    id: "M067",
    itemName: "ondansetron 4 MG Disintegrating Oral Tablet",
    itemType: "Disintegrating Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "DISINTEGRATING TABLET",
    drugMeasurement: "Each",
    genericName: "ondansetron",
    strength: "4",
    usage: "ORAL",
    stock: 120
  },
  {
    id: "M068",
    itemName: "lamotrigine 100 MG Oral Tablet [Lamictal]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "lamotrigine",
    strength: "100",
    usage: "ORAL",
    stock: 90
  },
  {
    id: "M069",
    itemName: "lamotrigine 25 MG Oral Tablet [Lamictal]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "lamotrigine",
    strength: "25",
    usage: "ORAL",
    stock: 100
  },
  {
    id: "M070",
    itemName: "gabapentin 100 MG Oral Capsule [Neurontin]",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "gabapentin",
    strength: "100",
    usage: "ORAL",
    stock: 300
  },
  {
    id: "M071",
    itemName: "gabapentin 300 MG Oral Capsule [Neurontin]",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "gabapentin",
    strength: "300",
    usage: "ORAL",
    stock: 250
  },
  {
    id: "M072",
    itemName: "gabapentin 400 MG Oral Capsule [Neurontin]",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "gabapentin",
    strength: "400",
    usage: "ORAL",
    stock: 220
  },
  {
    id: "M073",
    itemName: "bromocriptine 5 MG Oral Capsule [Parlodel]",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "bromocriptine",
    strength: "5",
    usage: "ORAL",
    stock: 45
  },
  {
    id: "M074",
    itemName: "nicotine 4 MG Chewing Gum [Nicorette]",
    itemType: "Chewing Gum",
    itemCategory: "Gums",
    drugFormName: "GUM",
    drugMeasurement: "Each",
    genericName: "nicotine",
    strength: "4",
    usage: "OTHER",
    stock: 500
  },
  {
    id: "M075",
    itemName: "cefadroxil 100 MG/ML Oral Suspension",
    itemType: "Oral Suspension",
    itemCategory: "Liquids",
    drugFormName: "SUSPENSION",
    drugMeasurement: "ML",
    genericName: "cefadroxil",
    strength: "100",
    usage: "ORAL",
    stock: 120
  },
  {
    id: "M076",
    itemName: "cefotaxime 200 MG/ML Injectable Solution [Claforan]",
    itemType: "Injectable Solution",
    itemCategory: "Injectables",
    drugFormName: "INJECTABLE SOLUTION",
    drugMeasurement: "ML",
    genericName: "cefotaxime",
    strength: "200",
    usage: "PARENTERAL",
    stock: 60
  },
  {
    id: "M077",
    itemName: "azithromycin 40 MG/ML Oral Suspension [Zithromax]",
    itemType: "Oral Suspension",
    itemCategory: "Liquids",
    drugFormName: "SUSPENSION",
    drugMeasurement: "ML",
    genericName: "azithromycin",
    strength: "40",
    usage: "ORAL",
    stock: 180
  },
  {
    id: "M078",
    itemName: "isoniazid 10 MG/ML Oral Solution",
    itemType: "Oral Solution",
    itemCategory: "Liquids",
    drugFormName: "ORAL SOLUTION",
    drugMeasurement: "ML",
    genericName: "isoniazid",
    strength: "10",
    usage: "ORAL",
    stock: 90
  },
  {
    id: "M079",
    itemName: "mebendazole 100 MG Chewable Tablet",
    itemType: "Chewable Tablet",
    itemCategory: "Tablets",
    drugFormName: "CHEWABLE TABLET",
    drugMeasurement: "Each",
    genericName: "mebendazole",
    strength: "100",
    usage: "ORAL",
    stock: 150
  },
  {
    id: "M080",
    itemName: "dexamethasone 0.5 MG Oral Tablet [Decadron]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "dexamethasone",
    strength: "0.5",
    usage: "ORAL",
    stock: 200
  },
  {
    id: "M081",
    itemName: "hydrocortisone 100 MG Injection [Solu-Cortef]",
    itemType: "Injection",
    itemCategory: "Injectables",
    drugFormName: "INJECTION",
    drugMeasurement: "ML",
    genericName: "hydrocortisone",
    strength: "100",
    usage: "PARENTERAL",
    stock: 100
  },
  {
    id: "M082",
    itemName: "bromocriptine 2.5 MG Oral Tablet [Parlodel]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "bromocriptine",
    strength: "2.5",
    usage: "ORAL",
    stock: 80
  },
  {
    id: "M083",
    itemName: "metyrapone 250 MG Oral Capsule [Metopirone]",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "metyrapone",
    strength: "250",
    usage: "ORAL",
    stock: 30
  },
  {
    id: "M084",
    itemName: "1 ML alprostadil 0.5 MG/ML Injection [Prostin VR]",
    itemType: "Injection",
    itemCategory: "Injectables",
    drugFormName: "INJECTION",
    drugMeasurement: "ML",
    genericName: "alprostadil",
    strength: "1",
    usage: "PARENTERAL",
    stock: 15
  },
  {
    id: "M085",
    itemName: "busulfan 2 MG Oral Tablet [Myleran]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "busulfan",
    strength: "2",
    usage: "ORAL",
    stock: 50
  },
  {
    id: "M086",
    itemName: "carmustine 100 MG Injection [BiCNU]",
    itemType: "Injection",
    itemCategory: "Injectables",
    drugFormName: "INJECTION",
    drugMeasurement: "ML",
    genericName: "carmustine",
    strength: "100",
    usage: "PARENTERAL",
    stock: 25
  },
  {
    id: "M087",
    itemName: "chlorambucil 2 MG Oral Tablet [Leukeran]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "chlorambucil",
    strength: "2",
    usage: "ORAL",
    stock: 45
  },
  {
    id: "M088",
    itemName: "melphalan 2 MG Oral Tablet [Alkeran]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "melphalan",
    strength: "2",
    usage: "ORAL",
    stock: 40
  },
  {
    id: "M089",
    itemName: "dactinomycin 0.5 MG Injection [Cosmegen]",
    itemType: "Injection",
    itemCategory: "Injectables",
    drugFormName: "INJECTION",
    drugMeasurement: "ML",
    genericName: "dactinomycin",
    strength: "0.5",
    usage: "PARENTERAL",
    stock: 20
  },
  {
    id: "M090",
    itemName: "fluorouracil 50 MG/ML Topical Cream",
    itemType: "Topical Cream",
    itemCategory: "Topicals",
    drugFormName: "CREAM",
    drugMeasurement: "Gram",
    genericName: "fluorouracil",
    strength: "50",
    usage: "TOPICAL",
    stock: 55
  },
  {
    id: "M091",
    itemName: "methotrexate 2.5 MG Oral Tablet",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "methotrexate",
    strength: "2.5",
    usage: "ORAL",
    stock: 120
  },
  {
    id: "M092",
    itemName: "methotrexate 10 MG Oral Tablet",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "methotrexate",
    strength: "10",
    usage: "ORAL",
    stock: 100
  },
  {
    id: "M093",
    itemName: "thioguanine 40 MG Oral Tablet [Tabloid]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "thioguanine",
    strength: "40",
    usage: "ORAL",
    stock: 40
  },
  {
    id: "M094",
    itemName: "hydroxyurea 500 MG Oral Capsule [Hydrea]",
    itemType: "Oral Capsule",
    itemCategory: "Capsules",
    drugFormName: "CAPSULE",
    drugMeasurement: "Each",
    genericName: "hydroxyurea",
    strength: "500",
    usage: "ORAL",
    stock: 110
  },
  {
    id: "M095",
    itemName: "pentostatin 10 MG Injection [Nipent]",
    itemType: "Injection",
    itemCategory: "Injectables",
    drugFormName: "INJECTION",
    drugMeasurement: "ML",
    genericName: "pentostatin",
    strength: "10",
    usage: "PARENTERAL",
    stock: 15
  },
  {
    id: "M096",
    itemName: "azathioprine 50 MG Oral Tablet [Imuran]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "azathioprine",
    strength: "50",
    usage: "ORAL",
    stock: 130
  },
  {
    id: "M097",
    itemName: "goserelin 3.6 MG Drug Implant [Zoladex]",
    itemType: "Drug Implant",
    itemCategory: "Implants",
    drugFormName: "IMPLANT",
    drugMeasurement: "Each",
    genericName: "goserelin",
    strength: "3.6",
    usage: "OTHER",
    stock: 40
  },
  {
    id: "M098",
    itemName: "aldesleukin 22000000 UNT Injection [Proleukin]",
    itemType: "Injection",
    itemCategory: "Injectables",
    drugFormName: "INJECTION",
    drugMeasurement: "ML",
    genericName: "aldesleukin",
    strength: "22000000",
    usage: "PARENTERAL",
    stock: 10
  },
  {
    id: "M099",
    itemName: "vitamin B12 0.05 MG Oral Tablet",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "vitamin B12",
    strength: "0.05",
    usage: "ORAL",
    stock: 300
  },
  {
    id: "M100",
    itemName: "diflunisal 250 MG Oral Tablet [Dolobid]",
    itemType: "Oral Tablet",
    itemCategory: "Tablets",
    drugFormName: "TABLET",
    drugMeasurement: "Each",
    genericName: "diflunisal",
    strength: "250",
    usage: "ORAL",
    stock: 80
  }
];
